let bank=[],mode='keypad',set=[],idx=0,score=0,typed={q:'',r:'',value:''},selectedChoice=null;
const $=s=>document.querySelector(s);const views=['home','quiz','puzzle','result'];
const state=JSON.parse(localStorage.getItem('amariPuzzleState')||'{"pieces":0,"world":0}');
const themes=['森のひみつ','海のたんけん','宇宙ステーション','恐竜の谷','おかしの国','空の王国','花の島','星空キャンプ','ふしぎな洞くつ','雲の上の町'];
function save(){localStorage.setItem('amariPuzzleState',JSON.stringify(state))}
function show(name){views.forEach(v=>$('#'+v).classList.toggle('hidden',v!==name));$('#homeBtn').classList.toggle('hidden',name==='home')}
function randSeed(n){let x=Math.sin(n*999+17)*43758.5453;return x-Math.floor(x)}
function sceneSvg(seed){const h=Math.floor(randSeed(seed)*360),h2=(h+80+Math.floor(randSeed(seed+1)*140))%360;let dots='';for(let i=0;i<24;i++){let x=Math.floor(randSeed(seed+i*3)*100),y=Math.floor(randSeed(seed+i*3+1)*100),r=1+Math.floor(randSeed(seed+i*3+2)*4);dots+=`<circle cx="${x}" cy="${y}" r="${r}" fill="hsla(${(h+i*7)%360},80%,70%,.75)"/>`}return `data:image/svg+xml;utf8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><defs><linearGradient id="g"><stop stop-color="hsl(${h},70%,82%)"/><stop offset="1" stop-color="hsl(${h2},78%,70%)"/></linearGradient></defs><rect width="100" height="100" fill="url(#g)"/>${dots}<path d="M0 78 Q20 55 40 76 T100 68 V100 H0Z" fill="hsla(${(h+140)%360},60%,38%,.55)"/><circle cx="${20+Math.floor(randSeed(seed+77)*60)}" cy="${20+Math.floor(randSeed(seed+78)*32)}" r="${8+Math.floor(randSeed(seed+79)*9)}" fill="hsla(${(h+45)%360},95%,65%,.9)"/></svg>`)}`}
function renderPuzzle(){const local=state.pieces%25,bg=sceneSvg(state.world+1);$('#worldTitle').textContent=`${themes[state.world%themes.length]}・${state.world+1}`;$('#totalPieces').textContent=state.pieces;$('#pieceText').textContent=`ピース ${state.pieces}`;$('#miniPuzzle').style.backgroundImage=`url("${bg}")`;const box=$('#jigsaw');box.innerHTML='';for(let i=0;i<25;i++){let p=document.createElement('div');p.className='piece'+(i<local?' on':'');p.style.backgroundImage=`url("${bg}")`;p.style.backgroundPosition=`${(i%5)*25}% ${Math.floor(i/5)*25}%`;box.appendChild(p)}$('#puzzleStatus').textContent=`この絵は ${local} / 25 ピース。次の絵は完成するまでひみつ！`}
function pick(cats,n){let pool=bank.filter(q=>cats.includes(q.category)),a=[];while(a.length<n&&pool.length){let k=Math.floor(Math.random()*pool.length);a.push(pool.splice(k,1)[0])}return a}
function makeSet(){set=[...pick(['計算','あまりの意味','確かめ'],4),...pick(['文章・基本','あまりを答える','切り上げ','切り捨て'],3),...pick(['誤答発見','図・表・会話','思考・判断'],3)].sort(()=>Math.random()-.5)}
function start(){makeSet();idx=0;score=0;show('quiz');renderQ()}
function renderQ(){typed={q:'',r:'',value:''};selectedChoice=null;const q=set[idx];$('#qCount').textContent=`${idx+1} / 10`;$('#catBadge').textContent=q.category;$('#barFill').style.width=`${(idx+1)*10}%`;$('#prompt').textContent=q.prompt;$('#feedback').className='feedback hidden';$('#feedback').textContent='';$('#nextBtn').classList.add('hidden');$('#checkBtn').classList.remove('hidden');$('#showAnswerBtn').classList.remove('hidden');$('#options').innerHTML=(q.options||[]).map((x,i)=>`<button class="option" data-v="${i+1}">${x}</button>`).join('');document.querySelectorAll('.option').forEach(b=>b.onclick=()=>{selectedChoice=+b.dataset.v;typed.value=String(selectedChoice);document.querySelectorAll('.option').forEach(x=>x.classList.toggle('active',x===b));updateDisplays()});renderAnswer(q)}
function renderAnswer(q){const a=$('#answerArea');a.innerHTML='';if(mode==='keypad'){a.innerHTML=keypadUI(q);document.querySelectorAll('[data-key]').forEach(b=>b.onclick=()=>pressKey(b.dataset.key,q))}else{a.innerHTML=handUI(q);setupCanvases()}}
function keypadUI(q){let labels=q.format==='qr'?'<div class="answerBox"><span>商</span><div id="dispQ" class="numDisplay"></div><span>あまり</span><div id="dispR" class="numDisplay"></div></div>':'<div class="answerBox"><span>答え</span><div id="dispV" class="numDisplay"></div></div>';return labels+`<div class="keypad">${[1,2,3,4,5,6,7,8,9].map(n=>`<button data-key="${n}">${n}</button>`).join('')}<button data-key="C">C</button><button data-key="0">0</button><button data-key="B">←</button></div>`}
function pressKey(k,q){let field=q.format==='qr'?(typed.q===''?'q':'r'):'value';if(k==='C')typed={q:'',r:'',value:''};else if(k==='B')typed[field]=typed[field].slice(0,-1);else if(q.format==='qr'){if(typed.q==='')typed.q=k;else typed.r=k}else typed[field]=(typed[field]+k).slice(0,2);updateDisplays()}
function updateDisplays(){if($('#dispQ'))$('#dispQ').textContent=typed.q;if($('#dispR'))$('#dispR').textContent=typed.r;if($('#dispV'))$('#dispV').textContent=typed.value}
function handUI(q){if(q.format==='qr')return '<div class="canvasWrap"><div class="handSlot"><b>商</b><canvas class="handCanvas" width="280" height="280"></canvas><button class="clearInk">消す</button></div><div class="handSlot"><b>あまり</b><canvas class="handCanvas" width="280" height="280"></canvas><button class="clearInk">消す</button></div></div><p class="note">書けたら「こたえあわせ」を押して、自分で○×をつけます。</p>';return '<div class="canvasWrap"><div class="handSlot"><b>答え</b><canvas class="handCanvas" width="280" height="280"></canvas><button class="clearInk">消す</button></div></div><p class="note">書けたら「こたえあわせ」を押して、自分で○×をつけます。</p>'}
function setupCanvases(){document.querySelectorAll('.handCanvas').forEach(c=>{let ctx=c.getContext('2d'),down=false;ctx.lineWidth=12;ctx.lineCap='round';ctx.strokeStyle='#173229';const pos=e=>{let r=c.getBoundingClientRect();return[(e.clientX-r.left)*c.width/r.width,(e.clientY-r.top)*c.height/r.height]};c.onpointerdown=e=>{down=true;let [x,y]=pos(e);ctx.beginPath();ctx.moveTo(x,y)};c.onpointermove=e=>{if(!down)return;let [x,y]=pos(e);ctx.lineTo(x,y);ctx.stroke()};c.onpointerup=()=>down=false;c.onpointerleave=()=>down=false});document.querySelectorAll('.clearInk').forEach((b,i)=>b.onclick=()=>{let c=document.querySelectorAll('.handCanvas')[i];c.getContext('2d').clearRect(0,0,c.width,c.height)})}
function answerText(q){return q.format==='qr'?`${q.answer.q} あまり ${q.answer.r}`:String(q.answer.value)}
function check(){const q=set[idx];if(mode==='hand'){const f=$('#feedback');f.className='feedback answer';f.innerHTML=`正しい答えは <b>${answerText(q)}</b><br>${q.explanation}<div class="selfCheck"><button id="selfO" class="primary">○ あっていた</button><button id="selfX" class="secondary">× なおそう</button></div>`;$('#checkBtn').classList.add('hidden');$('#showAnswerBtn').classList.add('hidden');$('#selfO').onclick=()=>revealFeedback(q,true);$('#selfX').onclick=()=>revealFeedback(q,false);return}let ok=q.format==='qr'?(+typed.q===q.answer.q&&+typed.r===q.answer.r):(+typed.value===q.answer.value);revealFeedback(q,ok)}
function revealFeedback(q,ok){if(ok)score++;const f=$('#feedback');f.className=`feedback ${ok?'ok':'ng'}`;f.innerHTML=ok?`⭕ せいかい！<br>${q.explanation}`:`△ もう一度考えてみよう。<br>答え：<b>${answerText(q)}</b><br>${q.explanation}`;$('#checkBtn').classList.add('hidden');$('#showAnswerBtn').classList.add('hidden');$('#nextBtn').classList.remove('hidden')}
function showAnswer(){const q=set[idx],f=$('#feedback');f.className='feedback answer';f.innerHTML=`💡 答え：<b>${answerText(q)}</b><br>${q.explanation}<br><small>答えを見ても大丈夫。分かったことが次の力になります。</small>`;$('#checkBtn').classList.add('hidden');$('#showAnswerBtn').classList.add('hidden');$('#nextBtn').classList.remove('hidden')}
function next(){if(++idx<10)renderQ();else finish()}
function finish(){const earned=2+Math.floor(score/2);state.pieces+=earned;while(state.pieces>=25*(state.world+1))state.world++;save();renderPuzzle();$('#scoreText').textContent=`${score} / 10 問 せいかい`;$('#pieceEarned').textContent=`チャレンジで ${earned} ピース GET！`;show('result')}
document.querySelectorAll('.modeBtn').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('.modeBtn').forEach(x=>x.classList.toggle('selected',x===b));$('#modeNote').textContent=mode==='keypad'?'テンキーは自動で答え合わせします。':'手書きは、自分で○×をつける自己採点方式です。'});
$('#startBtn').onclick=start;$('#againBtn').onclick=start;$('#nextBtn').onclick=next;$('#checkBtn').onclick=check;$('#showAnswerBtn').onclick=showAnswer;$('#homeBtn').onclick=()=>{if(confirm('この10問を途中でやめてホームに戻りますか？'))show('home')};$('#puzzleBtn').onclick=()=>{renderPuzzle();show('puzzle')};$('#resultPuzzleBtn').onclick=()=>{renderPuzzle();show('puzzle')};$('#puzzleHome').onclick=()=>show('home');$('#resultHomeBtn').onclick=()=>show('home');
fetch('questions.json').then(r=>r.json()).then(d=>{bank=d.questions;renderPuzzle()}).catch(()=>alert('問題データを読み込めませんでした。'));
